# Generated by Django 5.1.1 on 2024-12-02 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="billing_address",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="city",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="shipping_address",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="state",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="zipcode",
        ),
    ]
