version: "3.9"

services:
  app:
    build:
      context: .
    container_name: dropshop_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - docker.env
    networks:
      - dropshop_network

  redis:
    image: redis:7.0
    container_name: dropshop_redis
    ports:
      - "6379:6379"
    networks:
      - dropshop_network

networks:
  dropshop_network:
    driver: bridge
