# Generated by Django 5.1.1 on 2024-10-01 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("order_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_number", models.CharField(max_length=100, unique=True)),
                ("carrier", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                            ("out_for_delivery", "Out for Delivery"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "current_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("estimated_delivery", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_info",
                        to="order_management.order",
                    ),
                ),
            ],
        ),
    ]
