# Generated by Django 5.1.1 on 2024-10-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordertracking",
            name="failure_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
