# Generated by Django 5.0.7 on 2024-09-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_admin",
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
