# Generated by Django 5.1.1 on 2024-10-10 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_management", "0002_order_payment_status_alter_order_status"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaystackPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reference", models.CharField(max_length=100, unique=True)),
                ("status", models.CharField(max_length=20)),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "access_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paystack_payments",
                        to="order_management.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paystack Payment",
                "verbose_name_plural": "Paystack Payments",
            },
        ),
    ]
