# Generated by Django 5.1.1 on 2024-10-08 05:58

import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_management", "0002_productreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                storage=storages.backends.gcloud.GoogleCloudStorage(),
                upload_to="product_images/",
            ),
        ),
    ]
