# Generated by Django 5.1.1 on 2024-10-08 06:03

import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_management", "0003_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                storage=storages.backends.gcloud.GoogleCloudStorage(),
                upload_to="media/product_images/",
            ),
        ),
    ]
