# Generated by Django 5.1.1 on 2024-10-13 18:25

import django.db.models.deletion
import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_management", "0004_alter_productimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="memory_size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="VariantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=storages.backends.gcloud.GoogleCloudStorage(),
                        upload_to="media/variant_images/",
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=255, null=True)),
                ("is_main", models.BooleanField(default=False)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="inventory_management.productvariant",
                    ),
                ),
            ],
        ),
    ]
