# Generated by Django 5.1.1 on 2024-10-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory_management",
            "0005_productvariant_color_productvariant_memory_size_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="variantimage",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
