# Generated by Django 5.1.1 on 2024-12-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory_management",
            "0009_remove_variantimage_variant_delete_productvariant_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="productreview",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="productreview",
            name="name",
            field=models.CharField(default="unknown", max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="productreview",
            name="user",
        ),
    ]
