# Generated by Django 5.1.1 on 2024-12-02 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_management", "0010_alter_productreview_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together={("product", "name")},
        ),
    ]
