# Generated by Django 5.1.1 on 2024-12-02 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_management", "0011_alter_productreview_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="supplier",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Supplier",
        ),
    ]
