# Generated by Django 5.1.1 on 2024-12-02 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory_management",
            "0012_remove_product_category_remove_product_supplier_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together=set(),
        ),
    ]
