# Generated by Django 5.1.1 on 2024-12-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_management", "0013_alter_productreview_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together={("product", "name")},
        ),
    ]
