# Generated by Django 5.1.1 on 2024-10-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("unpaid", "Unpaid"), ("paid", "Paid"), ("failed", "Failed")],
                default="unpaid",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("canceled", "Canceled"),
                    ("failed_delivery", "Failed Delivery"),
                    ("returned", "Returned"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
