# Generated by Django 5.1.1 on 2024-10-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_management", "0002_order_payment_status_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="return_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="return_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="return_requested",
            field=models.BooleanField(default=False),
        ),
    ]
