# Generated by Django 5.1.1 on 2024-12-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_management", "0003_order_return_approved_order_return_reason_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(default="nonnullable@gmail.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(default="unknown", max_length=255),
            preserve_default=False,
        ),
    ]
