# Generated by Django 5.1.1 on 2024-12-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_management", "0004_remove_order_user_order_email_order_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
