# Generated by Django 5.1 on 2024-09-04 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricing",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="pricing",
            name="start_date",
        ),
    ]
