# Generated by Django 5.1.1 on 2024-09-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_management", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="promotional_code",
            new_name="promotion_code",
        ),
        migrations.AlterField(
            model_name="promotioncode",
            name="expiration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
